### ISSUE TITLE
Wrong attribution on posts from ecdtools.eclipse.org

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/ecdtools.eclipse.org#213]
**Describe the bug**
Posts that come from https://ecdtools.eclipse.org/resources/blogs/ when showing in Planet Eclipse have @chrisguindon listed as the author, and not the actual post author. This would be the person who submitted the PR for the post or is added in the post metadata.

Note this is for original posts there, not posts pulled in from other sources.

**To Reproduce**
1. Go to https://planeteclipse.org/planet/
2. Find a post from https://ecdtools.eclipse.org/resources/blogs/
3. Observe the 'by ...' line underneath the post title.

**Expected behavior**
The post should be by the person who submitted the PR of the post, or perhaps there is an author variable that can be added to the post metadata.

**Screenshots**

<img width="1142" alt="Screenshot 2022-01-20 at 16 41 51" src="https://user-images.githubusercontent.com/114116/150382765-d42871e4-51dd-4d08-ba81-9c5a20136212.png">

**Additional context**
I am wondering why there are 2 by lines, one under the title and one under the post summary.

**Comment by chrisguindon** [comment]
The quick fix, for now, would be to update some generic information here:
https://github.com/EclipseFdn/ecdtools.eclipse.org/blob/master/config.toml#L42

How about we set the author to:
EClipse Cloud Dev Tools

What email should we use here?

I understand we need to set an author per field. I don't believe this feature is baked in hugo. We would need to add this feature to our hugo-theme. I will open an issue for that.

**Comment by chrisguindon** [comment]
The author is coming from this field: https://ecdtools.eclipse.org/resources/blogs/index.xml

**Comment by chrisguindon** [comment]
> Additional context
I am wondering why there are 2 by lines, one under the title and one under the post summary.

I don't think there is a good reason. I think it's simply because it's always been that way.

**Comment by linkfang** [comment]
@chrisguindon as the rss.xml has been updated, do we also need to update the blogs that already published on ecdtools or are we good to close this issue now and make sure future blogs will have proper author info?

**Comment by linkfang** [comment]
No, not yet

**Comment by chrisguindon** [comment]
I think we can close the issue once the ecdtools.eclipse.org is built using a version of our Hugo theme with your patch.

**Comment by chrisguindon** [comment]
@croundy Do you need us to change the author of any of the current blog post on the website? 

If so, please let us know which post we need update. We need the name + email of the author in order to make an update.

**Comment by linkfang** [comment]
Cool!
I will make a small patch for the documentation and update the hugo-theme here with the new release.

**Comment by linkfang** [comment]
Closing the issue.

Hi @croundy , please feel free to reopen the issue (or ping me to reopen it) if you would like to update any post for the author info.
As [Chris mentioned above](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/213#issuecomment-1054384510), we need the name + email of the author for an update.

Thanks!

**Comment by croundy** [comment]
> Closing the issue.
> 
> Hi @croundy , please feel free to reopen the issue (or ping me to reopen it) if you would like to update any post for the author info. As [Chris mentioned above](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/213#issuecomment-1054384510), we need the name + email of the author for an update.
> 
> Thanks!

@linkfang Looking at the blog posts, it seems everything is attributed properly. Am assuming the issue is fixed. Thanks!

**Comment by linkfang** [comment]
> @linkfang Looking at the blog posts, it seems everything is attributed properly. Am assuming the issue is fixed. Thanks!

On ecdtools website, I think so. But on https://planeteclipse.org/planet/, it's still not showing the actual author of the post.

For example, when you search "The DISCO Experience" and the one under Eclipse Cloud DevTools is showing Chris as the author. (It will use the website author as the default value if we don't specify an author)

Here is a screenshot of it: 
![image](https://user-images.githubusercontent.com/43075439/158239806-ae58be5e-e471-405d-b0cd-d98965235696.png)

**Comment by chrisguindon** [comment]
@linkfang Let me summarize to make sure I understand where we are at with this...

The template has been updated with our latest update. However, I am still being reported to the author since we did not update the author value for each post.

@linkfang I assume that you need @croundy to tell you who is the actual author of each post?

**Comment by linkfang** [comment]
> @linkfang Let me summarize to make sure I understand where we are at with this...
> 
> The template has been updated with our latest update. However, I am still being reported to the author since we did not update the author value for each post.
> 
> @linkfang I assume that you need @croundy to tell you who is the actual author of each post?

Yes, correct!

**Comment by linkfang** [comment]
@croundy , I should have included this list earlier, but here are the blogs that are missing author info:

- Eclipse Theia Builds Momentum
- Cloud IDE Day 2021 - A Great Success!
- 5 Reasons to Adopt Eclipse Theia
- Diagram Editors for Web-based Tools with Eclipse GLSP
- Cloud DevTools Community Update - October 2021
- Moving Embedded Software Development Tools into the Cloud
- Eclipse Cloud DevTools Contributor Award: Improving the Migration Guide for Eclipse Theia
- Internationalization in Eclipse Theia
- Eclipse Cloud DevTools Contributor Award: The DISCO Experience

If we would like to update the author of any of them, I will need the name and email address of the author. Thanks!

**Comment by croundy** [comment]
Thanks @linkfang and @chrisguindon. This helps. Author for all these posts should be attributed to Brian King.  

> @croundy , I should have included this list earlier, but here are the blogs that are missing author info:
> 
> * Eclipse Theia Builds Momentum


> * Cloud IDE Day 2021 - A Great Success!
> * 5 Reasons to Adopt Eclipse Theia
> * Diagram Editors for Web-based Tools with Eclipse GLSP
> * Cloud DevTools Community Update - October 2021
> * Moving Embedded Software Development Tools into the Cloud
> * Eclipse Cloud DevTools Contributor Award: Improving the Migration Guide for Eclipse Theia
> * Internationalization in Eclipse Theia
> * Eclipse Cloud DevTools Contributor Award: The DISCO Experience
> 
> https://ecdtools.eclipse.org/resources/blogs/
> 
> If we would like to update the author of any of them, I will need the name and email address of the author. Thanks!

**Comment by linkfang** [comment]
@croundy , as @autumnfound found out, the author of [Internationalization in Eclipse Theia](https://ecdtools.eclipse.org/resources/blogs/2021-12-16-theia-i18n/) was claimed to be Mark Sujew, so I assume we will set Mark Sujew as the author of the blog then?

**Comment by croundy** [comment]
> as @autumnfound found out, the author of [Internationalization in Eclipse Theia](https://ecdtools.eclipse.org/resources/blogs/2021-12-16-theia-i18n/) was claimed to be Mark Sujew, so I assume we will set Mark Sujew as the author of the blog then?

@linkfang You're right and good catch. That should be attributed to Mark Sujew. Thanks!

**Comment by linkfang** [comment]
Now the update for author info is live on prod (https://planeteclipse.org/planet/)

![image](https://user-images.githubusercontent.com/43075439/158685614-5aa8b60b-850e-453e-bb64-e1e06ed4cb93.png)

**Comment by chrisguindon** [comment]
@linkfang I don't think we should be publishing Brian's Email. The email is no longer valid but I would prefer we use his old work email for this: brian.king@eclipse-foundation.org.

Sorry @linkfang I should of catched that!

**Comment by linkfang** [comment]
No problem! 
The email change is live now!
